### ISSUE TITLE
Change color of mouse pointer

### ISSUE THREAD

**Issue by serghiou** [tkrabel/rstudio_atom_theme#1]
That's a fantastically useful article, thank you! I am just wondering whether you know of a way to change the color of the mouse pointer; it is extremely hard to see with a dark background. I have tried changing `.ace_cursor, .ace_string.ace_regexp {color: #D30102}`, but it only changes the color of the cursor, not of the pointer. Thank you very much again!

**Comment by serghiou** [comment]
Apologies! Just solved by adding this line I got from StackOverflow:

`.ace_editor *, input.GNKRCKGCKS { cursor: -webkit-image-set(url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=') 1x, url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAz0lEQVRIx2NgYGBY/R8I/vx5eelX3n82IJ9FxGf6tksvf/8FiTMQAcAGQMDvSwu09abffY8QYSAScNk45G198eX//yev73/4///701eh//kZSARckrNBRvz//+8+6ZohwCzjGNjdgQxkAg7B9WADeBjIBqtJCbhRA0YNoIkBSNmaPEMoNmA0FkYNoFKhapJ6FGyAH3nauaSmPfwI0v/3OukVi0CIZ+F25KrtYcx/CTIy0e+rC7R1Z4KMICVTQQ14feVXIbR695u14+Ir4gwAAD49E54wc1kWAAAAAElFTkSuQmCC') 2x) 5 8, text; }`

**Comment by tkrabel** [comment]
Hey Stylianos,

 

I am glad you like the article. Thanks for the info. I personally haven't had a problem with the color of the mouse pointer, but I haven't thought of a solution myself and will definitely tray out yours!

 

Have a nice day!

Cheers,

Tobias

 

Gesendet: Dienstag, 05. Juni 2018 um 09:54 Uhr
Von: "Stylianos Serghiou" <notifications@github.com>
An: tkrabel/rstudio_atom_theme <rstudio_atom_theme@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [tkrabel/rstudio_atom_theme] Change color of mouse pointer (#1)


Apologies! Just solved by adding this line I got from StackOverflow:

.ace_editor *, input.GNKRCKGCKS { cursor: -webkit-image-set(url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=') 1x, url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAz0lEQVRIx2NgYGBY/R8I/vx5eelX3n82IJ9FxGf6tksvf/8FiTMQAcAGQMDvSwu09abffY8QYSAScNk45G198eX//yev73/4///701eh//kZSARckrNBRvz//+8+6ZohwCzjGNjdgQxkAg7B9WADeBjIBqtJCbhRA0YNoIkBSNmaPEMoNmA0FkYNoFKhapJ6FGyAH3nauaSmPfwI0v/3OukVi0CIZ+F25KrtYcx/CTIy0e+rC7R1Z4KMICVTQQ14feVXIbR695u14+Ir4gwAAD49E54wc1kWAAAAAElFTkSuQmCC') 2x) 5 8, text; }
